motd: A python-based minecraft server
max-players: 20
groups:
  Member:
    p:
      - core.place
      - core.break
      - core.
  Owner:
    p: # List of permissions
      - "*"
    u: # Users in this group
      - FranchuFranchu
    g: # Groups it inherits permissions and users from
      - Member