motd: A python-based minecraft server
max-players: 20
groups:
  Member:
    p:
      - core.place
      - core.break
      - stdchat.format.*
      - stdchat.
    d:
      pretext: "&7"
    u: # Users in this group
      - FranchuFranchu
  Owner:
    p: # List of permissions
      - "*"
    d: # Plugin data
      prefix: "[&4OWNER&f]"
    u: # Users in this group
      - FranchuFranchu
    g: # Groups it inherits permissions and users from
      - Member